apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: mortgage
    user: postgres
    editable: false
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
