"""
Multi-Model Credit Scoring Trainer
====================================
Trains LogisticRegression (baseline), XGBoost, and LightGBM.
Uses REAL data from data/train.csv (generated by data/pipeline.py).
Saves all models + comparison report to /models/

DESIGN DECISIONS:
1. Three-way split (Train/Val/Test) prevents data leakage in early stopping.
2. Winner selection based on mean Cross-Validation AUC (more robust than single test AUC).
3. Fixed seed=42 by default for full reproducibility. Override with --seed CLI argument.

Usage:
    python -m ml.training.train              # seed=42 (reproducible)
    python -m ml.training.train --seed 123   # custom seed
"""

import argparse
import os
import sys
import json
import time
import warnings
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, roc_auc_score, average_precision_score, f1_score,
    precision_score, recall_score, brier_score_loss, classification_report,
    confusion_matrix
)
import xgboost as xgb
import lightgbm as lgb
import joblib

warnings.filterwarnings("ignore")

# ─── Project root ──────────────────────────────────────────────────────────────
_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = _ROOT / "models"
DATA_DIR   = _ROOT.parent / "data" if (_ROOT.parent / "data" / "train.csv").exists() else _ROOT / "data"
MODELS_DIR.mkdir(exist_ok=True)

# Add root to path for imports
sys.path.insert(0, str(_ROOT))

# Import the canonical feature list
from ml.inference.predict import MODEL_FEATURES
# Import shared CV utilities — same code used by train.py and evaluate.py
from ml.training.eval_utils import compute_cv_auc

FEATURE_NAMES = MODEL_FEATURES
TARGET_COL    = "target"

# ─── 1. DATA ───────────────────────────────────────────────────────────────────

def load_data(seed: int = 42):
    """
    Load canonical train / val / test splits produced by data/pipeline.py.

    Consumes train.csv (SMOTE-balanced), val.csv, and test.csv DIRECTLY without
    re-merging or re-splitting.  This guarantees:
    - Test set contains ONLY real (non-synthetic) records.
    - Validation set contains ONLY real records.
    - SMOTE-generated samples are confined to the training split.

    Falls back to synthetic data only if all three CSV files are absent.
    """
    train_path = DATA_DIR / "train.csv"
    val_path   = DATA_DIR / "val.csv"
    test_path  = DATA_DIR / "test.csv"

    if train_path.exists() and val_path.exists() and test_path.exists():
        print(f"Loading canonical splits from {DATA_DIR}...")
        train_df = pd.read_csv(train_path)
        val_df   = pd.read_csv(val_path)
        test_df  = pd.read_csv(test_path)

        # Validate columns against the canonical schema
        missing = [c for c in FEATURE_NAMES + [TARGET_COL] if c not in train_df.columns]
        if missing:
            print(f"  [WARN] Missing columns in train.csv: {missing}. Falling back to synthetic.")
            return _synthetic_data(seed)

        X_train = train_df[FEATURE_NAMES]
        y_train = train_df[TARGET_COL]
        X_val   = val_df[FEATURE_NAMES]
        y_val   = val_df[TARGET_COL]
        X_test  = test_df[FEATURE_NAMES]
        y_test  = test_df[TARGET_COL]

        print(f"  Train: {len(X_train):,}  |  Val: {len(X_val):,}  |  Test: {len(X_test):,}")
        print(f"  Train default rate : {float(y_train.mean()):.1%}  (SMOTE-balanced)")
        print(f"  Val   default rate : {float(y_val.mean()):.1%}")
        print(f"  Test  default rate : {float(y_test.mean()):.1%}")
        return X_train, X_val, X_test, y_train, y_val, y_test

    print("One or more data CSVs missing — generating synthetic dataset...")
    print("  Run: python data/pipeline.py  to generate real splits.")
    return _synthetic_data(seed)


def _synthetic_data(seed: int = 42):
    """Generate synthetic data matching MODEL_FEATURES schema."""
    from sklearn.datasets import make_classification

    np.random.seed(seed)
    n = 10_000

    X_raw, y = make_classification(
        n_samples=n, n_features=15, n_informative=10, n_redundant=3,
        weights=[0.75, 0.25], random_state=seed,
    )

    # Realistic ranges per feature
    scaler_map = {
        "credit_score":                 (300, 850),
        "annual_income":                (20000, 200000),
        "loan_amount":                  (5000, 500000),
        "loan_term":                    (12, 360),
        "dti_ratio":                    (0.05, 0.95),
        "employment_years":             (0, 40),
        "num_credit_lines":             (1, 25),
        "num_derogatory_marks":         (0, 10),    # 90+ day lates
        "credit_utilization":           (0.0, 1.0),
        "late_payment_severity_score":  (0.0, 1.0), # severity-weighted composite
        "home_ownership":               (0, 2),
        "purpose_encoded":              (0, 9),
        "num_late_payments":            (0, 15),    # 30-59 day lates
        "savings_balance":              (0, 100000),
        "monthly_expenses":             (500, 8000),
    }

    X_scaled = np.zeros_like(X_raw)
    for i, feat in enumerate(FEATURE_NAMES):
        lo, hi = scaler_map[feat]
        col = X_raw[:, i]
        col_norm = (col - col.min()) / (col.max() - col.min() + 1e-8)
        X_scaled[:, i] = lo + col_norm * (hi - lo)

    X = pd.DataFrame(X_scaled, columns=FEATURE_NAMES)
    for col in ["loan_term", "num_credit_lines", "num_derogatory_marks",
                "home_ownership", "purpose_encoded", "num_late_payments"]:
        X[col] = X[col].round().astype(int)

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.4, random_state=seed, stratify=y
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.5, random_state=seed, stratify=y_temp
    )
    return X_train, X_val, X_test, y_train, y_val, y_test

# ─── 2. MODEL DEFINITIONS ──────────────────────────────────────────────────────

def build_models(y_train, seed: int = 42):
    """Build model definitions. Class weighting is not applied here because
    training data is already SMOTE-balanced by the data pipeline (50/50 ratio).
    XGBoost scale_pos_weight is computed from actual labels (will be ~1.0)."""
    pos_weight = (y_train == 0).sum() / max((y_train == 1).sum(), 1)
    from ml.inference.ensemble import MortgageEnsembleModel

    models = {
        "LogisticRegression": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(
                max_iter=1000, C=0.5,
                # No class_weight: data is SMOTE-balanced by pipeline
                random_state=seed,
            )),
        ]),

        "XGBoost": xgb.XGBClassifier(
            n_estimators=500, max_depth=6,
            learning_rate=0.03, subsample=0.8,
            colsample_bytree=0.8, min_child_weight=3,
            scale_pos_weight=pos_weight,  # ~1.0 with SMOTE-balanced data
            reg_alpha=0.2, reg_lambda=2.0,
            eval_metric="auc",
            early_stopping_rounds=50,
            random_state=seed, verbosity=0, n_jobs=-1,
        ),

        "LightGBM": lgb.LGBMClassifier(
            n_estimators=500, max_depth=6,
            learning_rate=0.03, num_leaves=31,
            subsample=0.8, colsample_bytree=0.8,
            min_child_samples=25,
            reg_alpha=0.2, reg_lambda=2.0,
            # No class_weight: data is SMOTE-balanced by pipeline
            early_stopping_rounds=50,
            random_state=seed, verbose=-1, n_jobs=-1,
        ),

        "Ensemble": MortgageEnsembleModel(random_state=seed),
    }
    return models

# ─── 3. TRAIN + EVALUATE ───────────────────────────────────────────────────────

def train_and_evaluate(models, X_train, X_val, X_test, y_train, y_val, y_test, seed: int = 42):
    """Train models using validation set for early stopping, then evaluate on test set.

    CV-AUC uses the shared compute_cv_auc() from eval_utils, which:
    - Creates early-stopping-free estimators for XGB/LGB.
    - Defers Ensemble nested CV to evaluate.py (allow_ensemble_cv=False here).
    """
    results = {}

    for name, model in models.items():
        print(f"\nTraining {name}...")
        t0 = time.time()

        # Fit with Early Stopping on Validation Set (prevents leakage)
        if name == "XGBoost":
            model.fit(X_train, y_train,
                      eval_set=[(X_val, y_val)], verbose=False)
        elif name == "LightGBM":
            model.fit(X_train, y_train,
                      eval_set=[(X_val, y_val)],
                      callbacks=[lgb.early_stopping(50, verbose=False)])
        else:
            model.fit(X_train, y_train)

        elapsed = time.time() - t0

        # Predictions on Test Set
        y_prob = model.predict_proba(X_test)[:, 1]

        # Optimal threshold (maximize F1 on val, then apply to test)
        y_prob_val = model.predict_proba(X_val)[:, 1]
        best_thresh, best_f1 = 0.5, 0.0
        for t in np.arange(0.2, 0.8, 0.01):
            f = f1_score(y_val, y_prob_val >= t, zero_division=0)
            if f > best_f1:
                best_f1, best_thresh = f, t

        y_pred_test = (y_prob >= best_thresh).astype(int)

        # Cross-val AUC on Train+Val via canonical shared utility
        # allow_ensemble_cv=False: defers the expensive nested CV to evaluate.py
        X_cv = pd.concat([X_train, X_val], axis=0)
        y_cv = pd.concat([y_train, y_val], axis=0)
        cv_result = compute_cv_auc(
            model, name, X_cv, y_cv,
            n_splits=5, seed=seed,
            allow_ensemble_cv=False,
        )
        cv_mean = cv_result["cv_auc_mean"]
        cv_std  = cv_result["cv_auc_std"]

        metrics = {
            "accuracy":          round(accuracy_score(y_test, y_pred_test), 4),
            "roc_auc":           round(roc_auc_score(y_test, y_prob), 4),
            "pr_auc":            round(average_precision_score(y_test, y_prob), 4),
            "brier_score":       round(brier_score_loss(y_test, y_prob), 4),
            "f1":                round(f1_score(y_test, y_pred_test, zero_division=0), 4),
            "precision":         round(precision_score(y_test, y_pred_test, zero_division=0), 4),
            "recall":            round(recall_score(y_test, y_pred_test, zero_division=0), 4),
            "cv_auc_mean":       cv_mean,
            "cv_auc_std":        cv_std,
            "train_time_s":      round(elapsed, 2),
            "optimal_threshold": round(best_thresh, 3),
            "confusion_matrix":  confusion_matrix(y_test, y_pred_test).tolist(),
        }
        if "cv_note" in cv_result:
            metrics["cv_note"] = cv_result["cv_note"]

        results[name] = metrics
        cv_display = f"{cv_mean:.4f}" if not (isinstance(cv_mean, float) and np.isnan(cv_mean)) else "N/A (see evaluate.py)"
        print(f"   AUC (Test): {metrics['roc_auc']:.4f} | CV-AUC: {cv_display}")

        # Save individual model
        save_name = name.lower().replace(" ", "")
        joblib.dump(model, MODELS_DIR / f"{save_name}.joblib")

    return results

def compute_importance(models):
    """Extract feature importances."""
    importance_data = {}
    for name, model in models.items():
        if name == "LogisticRegression":
            clf  = model.named_steps["clf"]
            imps = np.abs(clf.coef_[0])
        elif name in ("XGBoost", "LightGBM"):
            imps = model.feature_importances_
        else: continue
        imps = 100 * imps / (imps.sum() + 1e-10)
        importance_data[name] = dict(zip(FEATURE_NAMES, imps.round(2).tolist()))
    return importance_data

def save_report(results, models, importance_data):
    """Pick best model by CV-AUC (robustness), write report, set active.

    Ensemble is excluded from CV-based winner selection during training
    (its nested CV is deferred to evaluate.py). Winner is chosen from
    models that have a valid (non-NaN) cv_auc_mean.
    """
    # Only consider models with a valid CV-AUC for winner selection
    cv_candidates = [
        m for m in results
        if not (isinstance(results[m]["cv_auc_mean"], float)
                and np.isnan(results[m]["cv_auc_mean"]))
    ]
    if not cv_candidates:
        # Fallback: pick best by test ROC-AUC if all CV-AUCs failed
        winner = max(results, key=lambda m: results[m]["roc_auc"])
    else:
        winner = max(cv_candidates, key=lambda m: results[m]["cv_auc_mean"])

    def handle_nan(val):
        if isinstance(val, float) and np.isnan(val):
            return None
        return val

    # Clean metrics for JSON
    clean_results = {}
    for model_name, m_dict in results.items():
        clean_results[model_name] = {k: handle_nan(v) for k, v in m_dict.items()}

    report = {
        "winner":        winner,
        "metrics":       clean_results,
        "importance":    importance_data,
        "feature_names": FEATURE_NAMES,
        "last_updated":  datetime.now().isoformat()
    }

    with open(MODELS_DIR / "comparison_report.json", "w") as f:
        json.dump(report, f, indent=2)

    best_name = winner.lower().replace(" ", "")
    joblib.dump(models[winner], MODELS_DIR / "best_model.joblib")
    (MODELS_DIR / "best_model_name.txt").write_text(best_name)
    return winner

def run(seed: int = 42):
    print("=" * 62)
    print("  MORTGAGE AI — ROBUST MODEL TRAINER")
    print("=" * 62)
    print(f"  Global Random Seed: {seed}  (reproducible — use --seed to change)")

    X_train, X_val, X_test, y_train, y_val, y_test = load_data(seed)
    models = build_models(y_train, seed)
    results = train_and_evaluate(models, X_train, X_val, X_test, y_train, y_val, y_test, seed)
    importance_data = compute_importance(models)
    winner = save_report(results, models, importance_data)
    
    print("\n" + "=" * 62)
    print(f"  WINNER (by CV-AUC): {winner}")
    print("=" * 62)
    header = f"{'Model':<22} {'AUC':>7} {'PR-AUC':>8} {'Brier':>7} {'F1':>7} {'CV-AUC':>10}"
    print(header)
    print("-" * len(header))
    for name, m in results.items():
        flag = "  <-- winner" if name == winner else ""
        cv_mean = m.get("cv_auc_mean", float("nan"))
        cv_std  = m.get("cv_auc_std",  float("nan"))
        if isinstance(cv_mean, float) and np.isnan(cv_mean):
            cv_str = "N/A (see evaluate.py)"
        else:
            cv_str = f"{cv_mean:.4f}±{cv_std:.4f}"
        print(
            f"{name:<22} {m['roc_auc']:>7.4f} {m.get('pr_auc', 0):>8.4f} "
            f"{m.get('brier_score', 0):>7.4f} {m['f1']:>7.4f} "
            f"{cv_str:>20}{flag}"
        )
    
    return winner


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train all Mortgage AI models.")
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility (default: 42)",
    )
    args = parser.parse_args()
    run(seed=args.seed)